name: Lint and Auto-Fix Code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: pip install -r helpers/requirements.txt

      - name: Install Linting Tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black

      - name: Run Black Code Formatter (Auto-Fix)
        run: |
          black .

      - name: Run Flake8 (Verification Lint)
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. 
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

      - name: Commit and Push Fixed Code
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: automated lint and format fixes"
